var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/Mapas/Overpass/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__066b0jz._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0tej5c5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_179qmws.js")
R.c("server/chunks/ssr/[root-of-the-server]__00vx6id._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/src_20wfj1e._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_Mapas_Overpass_page_actions_12tfyai.js")
R.m(35096)
module.exports=R.m(35096).exports
